### PR TITLE
Fix invalid file path error on windows when applying patches

### PR DESCRIPTION
**Pull request by evanweible-wf**
Attempt at fixing #44

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by TimWhiting** [comment]
This fixes the issue.

**Review by robbecker-wf — APPROVED** [review]

**Comment by evanweible-wf** [comment]
QA +1
- [x] CI passes
- [x] https://github.com/Workiva/dart_codemod/pull/45#issuecomment-815441476

@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
