### PR TITLE
Fix `pathLooksLikeCode` to exclude build folder

### PR DESCRIPTION
**Pull request by smaifullerton-wk**
## Motivation
  
Codemods run on the `build/` folder after the package is built. Not only do we not want to do this, it can cause `generatePatches()` to throw an exception here and the codemod will fail: https://github.com/Workiva/dart_codemod/blob/master/lib/src/suggestors.dart#L191 

## Changes
  
Exclude paths starting with `build/` from the "looking like code" filter. 

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

Please review: 

### QA Checklist
- [ ] CI passes

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Client Platform member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/dart_codemod/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/dart_codemod/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by georgelesica-wf** [comment]
QA +1

**Comment by georgelesica-wf** [comment]
+1

**Comment by georgelesica-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
